### ISSUE TITLE
Find Security Bugs Status

### ISSUE THREAD

**Issue by karthikborkar** [find-sec-bugs/find-sec-bugs#236]
Recent i came across this mail thread :https://mailman.cs.umd.edu/pipermail/findbugs-discuss/2016-November/004321.html

Which states active development on the FindBugs project has been stopped. How is this going to affect Find Security Bugs plugin ?

Thanks

**Comment by h3xstream** [comment]
Basically, the development was stuck because the admin left without ever delegating management.  **A fork will take its place by the end of the year.**

I will not make any announcement until the new project prove to be a long term avenue. The compatibility with FindBugs will be kept for a long time as the API will not be change. Under the hood, "FindBugs" will change a lot.

This is the fork that is likely to become the "new FindBugs". The main developers have all move there.
https://github.com/spotbugs
