### ISSUE TITLE
Update JSP compiler 

### ISSUE THREAD

**Issue by h3xstream** [find-sec-bugs/find-sec-bugs#279]
Their is one dependency that is starting to look like a technical depth.. The old JSPC maven plugin.
![jspc](https://cloud.githubusercontent.com/assets/593130/23436487/b8379430-fdd8-11e6-8430-fc9ffff8509b.png)

Ref: https://www.versioneye.com/user/projects/5751d1e07757a00041b3a1dd

## SMAP support..

Currently the SMAP are analyze based on separate SMAP file? At that time, I did not know that SMAP are now embedded in class file. We can update the plugin if the test utility classes are updated accordingly..

**Comment by h3xstream** [comment]
Success : 

![badge](https://cloud.githubusercontent.com/assets/593130/23444355/9319fa7e-fe02-11e6-8f77-9ee539fe0905.png)

![version_eye_all_green](https://cloud.githubusercontent.com/assets/593130/23444344/81ccac26-fe02-11e6-8f52-8c2f7cca5a5c.png)

**Comment by ptamarit** [comment]
Hi,

Not sure if it's VersionEye being wrong or if you ran the check from another place than master, but it doesn't seem to match.
For instance, `logback-classic` is `1.1.7` in the root POM while the screenshot shows `1.2.1`.

In order to easily find dependencies and plugins upgrades from the CLI you can run:
* `mvn versions:display-dependency-updates`
* `mvn versions:display-plugin-updates`

As a side note, if you're interested I think it would be possible to ping automatically VersionEye and Coveralls after each commit on master from Travis CI. For instance, the last Coveralls check is from December 2015.

Cheers,
Pablo

**Comment by h3xstream** [comment]
VersionEye is poiting to the plugin pom.xml .. The scope of the checks is very limited..
My goal was just to catch the most important one.
In the end FindSecBugs is not package with any dependency. So this is not something big.

Yep. I was running coveralls manually. I learn about the secure configuration for travis-ci only recently. I will try to make it integrate to the build.
