### ISSUE TITLE
PermissiveCORSDetector throws NPE

### ISSUE THREAD

**Issue by tweea** [find-sec-bugs/find-sec-bugs#313]
I write a CORS Filter:
```java
@Component
public class SimpleCORSFilter extends OncePerRequestFilter {
	@Value("${application.cors.allow-origin}")
	private String allowOrigin;

	@Override
	public void doFilterInternal(HttpServletRequest request,
			HttpServletResponse response, FilterChain filterChain)
			throws IOException, ServletException {
		response.setHeader("Access-Control-Allow-Origin", allowOrigin);

		filterChain.doFilter(request, response);
	}
}
```
The PermissiveCORSDetector will throws a NullPointerException:
    java.lang.NullPointerException
      At com.h3xstream.findsecbugs.PermissiveCORSDetector.analyzeMethod(PermissiveCORSDetector.java:86)

When I change the variable 'allowOrigin' to a string literal, the NPE will not threw. It seems the PermissiveCORSDetector not support a variable parameter.

**Comment by h3xstream** [comment]
Note : This detector should be refactor to used Injection based detector pattern. see HardcodePasswordInMapDetector

**Comment by bradflood** [comment]
I am working on this. The code is refactored and existing tests pass. However new logic to catch issues with allow-origin values coming from servlet request parameter are not working. The generated bug report indicates "Possible XSS" instead of "Permissive CORS". @h3xstream is it possible the XSS rule has precedence and is actually correct? 
https://github.com/bradflood/find-sec-bugs/tree/issue313-permissiveCorsDetecter

**Comment by joffrey-bion** [comment]
Is there any target date for a release including this fix? This is impacting our builds and may prevent detection of further security issues.

**Comment by h3xstream** [comment]
@joffrey-bion On june 28, version 1.8.0 was release.
