### ISSUE TITLE
Documentation: how to remove "taint" from a variable?

### ISSUE THREAD

**Issue by RichardBradley** [find-sec-bugs/find-sec-bugs#346]
I haven't been able to figure out what santisation techniques the taint analysis engine understands.

See https://stackoverflow.com/questions/46571335/how-to-remove-taint-for-findbugs-find-security-bugs

The tool is identifying a possible injection bug from code like:
```java
import javax.ws.rs.core.Response;
import org.apache.http.client.methods.HttpGet;

public Response get(String x, String y) throws IOException {

    String url = String.format("%s/%s",
            x,
            y);

    HttpGet request = new HttpGet(url); // HERE

    ...
}
```
I have fixed this bug to my satisfaction with:

```java
import javax.ws.rs.core.Response;
import org.apache.http.client.methods.HttpGet;
import static com.google.common.net.UrlEscapers.urlPathSegmentEscaper;

public Response get(String x, String y) throws IOException {

    String url = String.format("%s/%s",
            urlPathSegmentEscaper().escape(x),
            urlPathSegmentEscaper().escape(y));

    HttpGet request = new HttpGet(url);

    ...
}
```
... but the tool is still flagging a possible bug. I believe that this is because it does not recognise "`com.google.common.net.UrlEscapers.urlPathSegmentEscaper()`" as removing Taint here.

How can I persuade it otherwise? If I cannot, what sanitisation techniques can I use here that the tool does recognise?

Are there some docs on this that I have missed?

Thanks!

**Comment by h3xstream** [comment]
# Background info

Every variable (`TaintFrame` internally ) has a state that evolve : [TAINTED, UNKNOWN, SAFE, ..](https://github.com/find-sec-bugs/find-sec-bugs/blob/e72c9a2fde79526be4cd0fa91f65e67b47d93940/plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/Taint.java#L45).
Most of injection based detector have `Tag` to track proper encoding. This will not affect the state of TaintFrame. But detector will look at those when determining if an value is safe or not.

Since you are looking to add the support for `com/google/common/escape/Escaper.escape()`. Here is an example of configuration for URLEncoder.
https://github.com/find-sec-bugs/find-sec-bugs/blob/a1a27aca43a0a4cc6ee680b3b978fa2916288f00/plugin/src/main/resources/safe-encoders/other.txt#L1-L4

The reason `com.google.common.net.UrlEscapers.urlPathSegmentEscaper()` is not recognized is most likely because it is a factory method.

**Comment by RichardBradley** [comment]
Thanks!

I have attempted to write this up for future users at https://github.com/find-sec-bugs/find-sec-bugs/wiki/Injection-detection

Please could you take a look and review it for correctness?

I will create a PR to link to that wiki page in the "References" section of the "Details" block for each injection detector, if you agree?

**Comment by h3xstream** [comment]
@RichardBradley The wiki is really good. It is an excellent introduction for new developers.

I would **not** add link to every description. I prefer to keep a focus on giving solution (secure code) and guideline rather than explaining how the FSB works internally.

**Comment by h3xstream** [comment]
`com/google/common/escape/Escaper.escape()` is generic interface mostly used for URL .. It would be a trade-off to consider this API as a URL encoder.

**Comment by RichardBradley** [comment]
> I would not add link to every description. 

Sure, I'll leave that then.

> com/google/common/escape/Escaper.escape() is a generic interface mostly used for URL .. It would be a trade-off to consider this API as a URL encoder.

Agreed. The API currently defined for the taint analysis doesn't let us do anything more fine-grained here though. I expect lots of people will be using the Guava escapers. I'm working on a PR for the Guava escapers and I'll make sure this is addressed (perhaps only in documentation).

The problem I'm having at the moment that motivated this issue is that I can't remove the injection warning (even though I think it fixed) and I'm not getting detailed enough diagnostics from the tool to see why it thinks there is an injection but I don't. (This is even after changing Escaper for URLEncoder). I'll see if I can isolate a repro case and add it here.

**Comment by h3xstream** [comment]
Precision to anyone looking to do the "good first issue".

The simple enhancement here is adding `com/google/common/escape/Escaper.escape()` as a valid escape method for URL encoding context.
