### ISSUE TITLE
False positive XSS when using OWASP taglib 

### ISSUE THREAD

**Issue by gvasquez-waypoint** [find-sec-bugs/find-sec-bugs#353]
Seems like the SonarQube plugin (or perhaps FindBugs itself) is not considering the use of the taglib version of the OWASP Encoder, as it is reporting a violation in the following excerpt:

`<br />MEDIANO PLAZO (${e:forHtmlContent(left)})<br />`

Considering:

`<%@taglib prefix="e" uri="https://www.owasp.org/index.php/OWASP_Java_Encoder_Project" %>`

SonarQube Version 6.5 (build 27846) 
FindBugs plugin: 3.6.0 installed (Analyze Java code with SpotBugs 3.1.0-RC6.)

Also posted at [SpotBugs](https://github.com/spotbugs/spotbugs/issues/485)

Ref: https://www.owasp.org/index.php/OWASP_Java_Encoder_Project#tab=Use_the_Java_Encoder_Project

**Comment by h3xstream** [comment]
Quick Note : This is a know limitation. "${e:forHtmlContent(left)}" is a dynamic expression that is compiled at runtime. JSP expression are not analyzed by FSB or more precisely consider as UNKNOWN.

There is still some plan to whitelist some specific strings.

**Comment by bradflood** [comment]
@h3xstream regarding the temporary fixes recommended above: the first option (`<e:forHtml value="${left}" />`) still shows as a violation findsecbugs-jsp:XSS_JSP_PRINT.  

I believe it is missed because the class (for example, `org.owasp.esapi.tags.EncodeForHTMLTag`) is not included in [owasp.txt](https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/resources/safe-encoders/owasp.txt)

**Comment by h3xstream** [comment]
@bradflood Excellent pointer. I assumed it was on the safe list.

**Comment by h3xstream** [comment]
The pattern `${e:forHtmlContent( [ascii name]  ) }` is now ignored. (No more FP)
