### ISSUE TITLE
Error in Creating New Detector Class

### ISSUE THREAD

**Issue by jyotigajrani** [find-sec-bugs/find-sec-bugs#372]
We are trying to implement new detector's for Android after identifying several vulnerabilities. We would like to contribute to find-sec-bugs after successful implementation. Firstly, we are trying for Android SQL Injection. 

Here, We are adding check for parameters of query() method.
If we do add our code as part of some existing detector then it is working fine and identifying vulnerability.
But if we add new detector for the same, it gives error on maven building.
we are following steps as (referencing https://github.com/find-sec-bugs/find-sec-bugs/wiki/Writing-a-detector) -
1. Added entry in findbugs.xml for new bug
2. Added entry in messages.xml
3. Created new detector class and added code to it.
4. Created test case...find-sec-bugs/plugin/src/test/java/android/
5. Created vulnerable sample in find-sec-bugs/plugin/src/test/testcode/android

But when we run it, We get error. For reference, We are attaching the screenshots of error.
And also the code of Test-case.

Please check and report what is the cause of error? Thanks in Advance

![screenshot from 2018-03-21 13-55-30](https://user-images.githubusercontent.com/12912589/37700136-5a9e8532-2d10-11e8-96c7-d44a40b098b0.png)
![screenshot from 2018-03-21 13-55-02](https://user-images.githubusercontent.com/12912589/37700139-5adf4c20-2d10-11e8-8ed3-83847764716b.png)

**Comment by h3xstream** [comment]
`reportBug` is the method called for every bug instance that were found during the analysis.
Bunch of bugs are reported because FindBugs core rules are enabled. This is where `UC: Useless object created` is coming from.
If you run the specific test cases from IntelliJ, you should see the bug reported in detail in the console.
When the test is run within Maven the output is slightly more compact and is harder to find among all the other tests.

## Maven surefire test
You might be able to find the output a specific test that failed from the HTML report. I still recommend **running test first in the IDE.**
![surefire-reports](https://user-images.githubusercontent.com/593130/37786551-5d852558-2dd3-11e8-89ec-0368f4e7e8c6.png)

## Fixing your build issues from IntelliJ

Run `mvn clean install` from the command line. Maven CLI never failed to download missing dependencies. The dependencies will be pickup if you reload your project.

From the IDE, you can achieve the same.
1. Refresh your Maven project. This will rescan all `pom.xml` and apply project changes needed including downloading missing dependency.
![refreshing](https://user-images.githubusercontent.com/593130/37786729-c11d15e4-2dd3-11e8-8f41-28e871397837.png)
2. Rebuild the project
![build_project](https://user-images.githubusercontent.com/593130/37786797-e7a4d85a-2dd3-11e8-8384-357cfbd8e99a.png)

You should not have any build errors in your idea because of missing artifacts.

My instruction might be too basic. Let me know if this solves your problem.

**Comment by jyotigajrani** [comment]
Thanks for the above answer.
But still I got issues regarding the same. I want to know how to resolve this UC: Useless object created ?
All the steps are properly followed by us and we did the exact same way as in the above description.
Also I need to ask you, why it is giving error in the arguments that are passed in the Test sample in doReportBug().

**Comment by jyotigajrani** [comment]
Hello,

I'm facing another issue regarding the test sample files. In most of the test cases which I'd created for the detectors, some of the methods and classes of android are neither importing and also there are errors.

I'm attaching the java files and the screenshot of error regarding the above issue. 
Other than this, we have made entries in findbugs.xml and messages.xml for bug.
This kind of error occurs in different test sample too.
Please check and inform the cause of error and how to handle it,

Thanks

![screenshot from 2018-03-24 13-08-05](https://user-images.githubusercontent.com/12912589/37861956-3c4bd1d6-2f6b-11e8-8f1e-a69ace3c612f.png)
[testing.zip](https://github.com/find-sec-bugs/find-sec-bugs/files/1844179/testing.zip)

**Comment by h3xstream** [comment]
The way we handle the compilation of test samples is using a stub project that regroups interface of various API. This allows us to avoid depending on couple hundred of jars. Making it easier to have multiple version of the same library. It's also much lighter, 247 kb for all the test dependencies.
https://github.com/find-sec-bugs/find-sec-bugs/tree/master/plugin-deps/src/main/java

The class ClipboardManager does not have a stub yet.

**Comment by h3xstream** [comment]
UC: Useless object created

It is just an artefact of running FindBugs with the core rules + findsecbugs. This means that your bugs were not found but other functional bugs (core rules) were founds. I did not manage to disable the core rules from the tests.

**Comment by h3xstream** [comment]
I assume all questions were answered.
