### ISSUE TITLE
False Positive XSS in Expression Language ${pageContext.request.contextPath}

### ISSUE THREAD

**Issue by bradflood** [find-sec-bugs/find-sec-bugs#399]
Using the JSP Expression Language to access the contextPath results in a Bug Instance

JSP source snippet
`<script type="text/javascript">var someURL = "${pageContext.request.contextPath}/app/foo"; </script>`

Resulting Bug Instance:
New Bug Instance: [2]
  message=SECXSS1: Potential XSS in JSP
  bugType=XSS_JSP_PRINT  priority=Medium  category=S
  class=org.apache.jsp.xss.xss_005ffsa_jsp  method=_jspService  line=126
  sources=[[org/apache/jasper/runtime/PageContextImpl.proprietaryEvaluate(Ljava/lang/String;Ljava/lang/Class;Ljavax/servlet/jsp/PageContext;Lorg/apache/jasper/runtime/ProtectedFunctionMapper;)Ljava/lang/Object;]]

This was generated from a unit test in a current fork of find-sec-bugs. 

@h3xstream in https://github.com/find-sec-bugs/find-sec-bugs/issues/353 you mention that FSB does not evaluate JSP expressions, but that there were plans to whitelist specific strings. Since the expression above references only objects managed by the container and not subject to user manipulation, this seems to be a candidate for whitelisting. 

If you agree and have some ideas on how to accomplish, please advise and I can submit a PR

**Comment by topolik** [comment]
Just a side note.

Currently there's a solution using https://github.com/find-sec-bugs/find-sec-bugs/blob/master/plugin/src/main/java/com/h3xstream/findsecbugs/taintanalysis/TaintMethodConfigWithArgumentsAndLocation.java

Such line compiles using Jasper to:
```
out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.evaluateExpression("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null));
```

The following line can be added to custom config file to tell the engine it's false-positive:
```
org/apache/jasper/runtime/PageContextImpl.evaluateExpression("${pageContext.request.contextPath}",SAFE,UNKNOWN,NULL):SAFE@org/apache/jsp/xss/xss_005ffsa_jsp
```

The definition can be specified using `-Dfindsecbugs.taint.customconfigfile=config-with-the-line-above.txt`

----

That being said, the `TaintMethodConfigWithArgumentsAndLocation` is very specific because it requires JSP class in the definition, however it can be improved to be more generic.

**Comment by bradflood** [comment]
PR https://github.com/find-sec-bugs/find-sec-bugs/pull/403 fixes this

**Comment by h3xstream** [comment]
`${pageContext.request.contextPath}` specifically is now covered.
