### ISSUE TITLE
Github actions - Configuration

### ISSUE THREAD

**Issue by pentagramz** [find-sec-bugs/find-sec-bugs#588]
How do I configure findsecbugs for just xss and sqli rules and ignore all other checks in maven configuration?

https://github.com/find-sec-bugs/find-sec-bugs/wiki/Maven-configuration

**Comment by h3xstream** [comment]
Good question. I have not played with Github action yet.

There is this project.. 
https://github.com/jwgmeligmeyling/spotbugs-github-action
I will test it soon.

**Comment by h3xstream** [comment]
## Configuration example

Here is a working configuration to run SpotBugs:

https://github.com/find-sec-bugs/find-sec-bugs/blob/791489a82b4b2bc38ab8b04e4e5ac6cda07d0746/.github/workflows/spotbugs.yml#L1-L26

## Result

https://github.com/find-sec-bugs/find-sec-bugs/runs/1034936823?check_suite_focus=true

You will get the complete list of issue on each build. I am not sure incremental report are made.

**Comment by h3xstream** [comment]
Since `mvn -B verify com.github.spotbugs:spotbugs-maven-plugin:3.1.12:spotbugs` is runned.. The detectors used will depend on the configuration of your pom.xml.

In the [Maven tutorial](https://github.com/find-sec-bugs/find-sec-bugs/wiki/Maven-configuration), you can see an `<includeFilterFile></includeFilterFile>` tag is configured. This file can contain the list of detector that you care about. Documentation on filtering options : https://spotbugs.readthedocs.io/en/latest/filter.html
